### ISSUE TITLE
Ability to track moving target element?

### ISSUE THREAD

**Issue by spencerjsmall** [fatihsolhan/v-onboarding#104]
Hi! First of all, thanks for building such a great package. I'm trying to build an onboarding tutorial in my app's VueFlow editor, however given that the user can pan and zoom within the editor, certain target elements pointed to by the tour may move around the screen. There unfortunately appears to be no way of updating a step's position (or have it reattach to the target). So, it was be awesome to have an `update` method exported by the useVOnboarding hook that I could repeatedly call on viewport change. If there are any existing workarounds to this, please let me know!

**Comment by spencerjsmall** [comment]
I was able to come up with a workaround for my specific usecase using the onMove VueFlow hook:
```
onMove((flowTransform) => {
  const stepElement = document.querySelectorAll('[data-popper-placement]')?.[0];
  const viewportTransform = flowTransform.flowTransform;
  const deltaX = viewportTransform.x - previousViewport.x;
  const deltaY = viewportTransform.y - previousViewport.y;

  if (stepElement) {
    const transform = stepElement.style.transform;
    const match = /translate3d\(([^,]+)px, ([^,]+)px, ([^,]+)px\)/.exec(
      transform,
    );
    if (match) {
      const currentX = parseFloat(match[1]);
      const currentY = parseFloat(match[2]);
      stepElement.style.transform = `translate3d(${currentX + deltaX}px, ${currentY + deltaY}px, 0px)`;
    }
  }

  previousViewport.x = viewportTransform.x;
  previousViewport.y = viewportTransform.y;
});
```

This feels like overkill though.

**Comment by fatihsolhan** [comment]
Hi @spencerjsmall 

Sorry for getting back to you so late on this one! 

I think I have a good solution for you - you can handle the moving elements by tweaking the Popper.js modifiers in the options. Here's what worked for me:

```typescript
const options: VOnboardingWrapperOptions = {
  popper: {
    modifiers: [
      {
        name: 'applyStyles',
        enabled: true,
        fn: ({ state }) => {
          Object.assign(state.elements.popper.style, {
            // You can dynamically update these values based on your viewport changes
            left: '100px',
            top: '200px',
            position: 'absolute'
          });
        }
      }
    ]
  }
}
```
See: https://popper.js.org/docs/v2/modifiers/apply-styles/

I'm closing this issue now, but feel free to reopen if you need any clarification or if this solution doesn't work for you! 👍
