### ISSUE TITLE
Ability to control where the overlay pops up

### ISSUE THREAD

**Issue by schachmatthias** [fatihsolhan/v-onboarding#105]
**Is your feature request related to a problem? Please describe.**
Maybe I am missing something, but as fast as Im aware there is no possibility to control where the overlay per step pops up, right?

**Describe the solution you'd like**
It would be nice to control it in the **_options_** per step flag. Similar to the scrollToStep, where you can say for example overlay: top, right, left, bottom, center etc

This would be useful especially if you have a long table you want to explain/highlight where as of now it would scroll down all the way to the bottom.

**Comment by schachmatthias** [comment]
Aaah nevermind. I didnt realize it uses the popper library up until now. 
So with
`options: {
placement: 'top'
}`

I got what I wanted. :)

**Comment by fatihsolhan** [comment]
Hey @schachmatthias you can override options per step https://v-onboarding-docs.fatihsolhan.com/props/steps
Check `options` key
