### ISSUE TITLE
Before and After functions doesn't work

### ISSUE THREAD

**Issue by gogo6ar** [fatihsolhan/v-onboarding#12]
**Describe the bug**
I have some steps and want to execute a function on last step. I  use example from documentation, but it doesn't work. I tried to add a log to "before" function, but have the same result.

**To Reproduce**
1. Copy example from documentation.
2. Add some logic (or simple console.log("xxx))
3. Check console.

**Expected behavior**
I expected that after (or before) executing a step I can add some logic (ex: go to another page).

**Screenshots**
![image](https://user-images.githubusercontent.com/30843716/159547413-1170bd4e-f5fb-43b9-b002-6193d1b65e9f.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [chrome]
 - Version [22]

**Comment by fatihsolhan** [comment]
@gogo6ar 

It looks like I mistyped the method names in the documentation.

It should work if you replace
`before` with `beforeStep`
`after` with `afterStep`

I will update the documentation shortly

**Comment by gogo6ar** [comment]
Thank you for help!
