### ISSUE TITLE
Could you add in the docs an example with an arrow?

### ISSUE THREAD

**Issue by ibrunotome** [fatihsolhan/v-onboarding#34]
**Is your feature request related to a problem? Please describe.**

I've followed the popper docs https://popper.js.org/docs/v2/modifiers/arrow/, I'm trying with your custom UI example https://v-onboarding-docs.fatihsolhan.com/examples/custom-ui, but the arrow never appears.

That's my custom step:

```js
  const steps = [
    {
      attachTo: { element: '#create_quest_button' },
      content: { title: 'Welcome!' },
      options: {
        popper: {
          modifiers: [
            {
              name: 'arrow',
              options: {
                padding: 5,
              },
            },
            {
              name: 'offset',
              options: {
                offset: [10, 20],
              },
            },
          ],
        },
      },
    },
  ]
```

**Describe the solution you'd like**
If possible, an example using arrow in the docs

**Comment by fatihsolhan** [comment]
@ibrunotome thank you for your interest in `v-onboarding` ❤️ 
I've added a default arrow to `v-onboarding`. If you want to change its appearance, [you can check this page](https://v-onboarding-docs.fatihsolhan.com/CSS/arrow)

**Comment by ibrunotome** [comment]
Thank you @fatihsolhan !
