### ISSUE TITLE
Exit or next can't work correctly when being last step with custom ui

### ISSUE THREAD

**Issue by warren30815** [fatihsolhan/v-onboarding#37]
**Describe the bug**
Hi, in the custom ui tutorial (https://v-onboarding-docs.fatihsolhan.com/examples/custom-ui)
the next function works fine when being not the last step
but when being the last step and click finish, there will be an error:
<img width="457" alt="Screen Shot 2022-06-29 at 7 10 14 PM" src="https://user-images.githubusercontent.com/36834814/176422808-dd624fc5-d13b-4e94-9b2b-e84f98394957.png">

**To Reproduce (template code)**

      <VOnboardingWrapper ref="wrapper" :steps="steps">
			<template
				#default="{
					previous,
					next,
					step,
					exit,
					isFirst,
					isLast,
					index,
				}"
			>
				<VOnboardingStep>
					<div class="bg-white shadow sm:rounded-lg">
						<div>
							<div v-if="step.content">
								<p>{{ step.content.title }}</p>
							</div>
							<div v-if="step.content.description">
								<p>{{ step.content.description }}</p>
							</div>
							<div>
								<template v-if="!isFirst">
									<ElButton @click="previous">
										Previous
									</ElButton>
								</template>
								<template v-if="!isLast">
									<ElButton @click="next"> Next </ElButton>
								</template>
								<template v-else>
									<ElButton @click="next"> Finish </ElButton>
								</template>
							</div>
						</div>
					</div>
				</VOnboardingStep>
			</template>
		</VOnboardingWrapper>

**To Reproduce (typescript + vue3 composition api code)**

      <script setup lang="ts">
      import {
	      VOnboardingWrapper,
	      VOnboardingStep,
	      useVOnboarding,
      } from 'v-onboarding'
      
      const wrapper = ref(null)
      const { start, goToStep, finish } = useVOnboarding(wrapper)
      const steps = [
	      {
		      attachTo: { element: '#foo' },
		      content: { title: 'Welcome!' },
	      },
	      {
		      attachTo: { element: '#bar' },
		      content: {
			      title: 'Do it!',
			      description: 'hi',
		      },
	      },
      ]
      </script>
Desktop (please complete the following information):
OS: 
macOS
Browser chrome
Version 103

Thanks!

**Comment by fatihsolhan** [comment]
Hi @warren30815, thank you for your interest in `v-onboarding`

Sorry for the late reply, but I just checked and it seemed working fine. Is it possible you have a selector that matches no element in the last step?

You can check the sandbox below. next/finish works fine with the custom UI
https://codesandbox.io/s/v-onboarding-1-2-1-test-78gw1b?file=/src/App.vue

If you still have this problem, please reproduce it and send me the codesandbox link

**Comment by ibrunotome** [comment]
Your codesandbox updading to v1.2.2 and clicking on `finish`.

<img width="1195" alt="Screen Shot 2022-07-02 at 14 48 11" src="https://user-images.githubusercontent.com/4256471/177011128-3da530d1-214c-4411-8676-59e87f34dfc7.png">

**Comment by fatihsolhan** [comment]
> Your codesandbox updading to v1.2.2 and clicking on `finish`.
> 
> <img alt="Screen Shot 2022-07-02 at 14 48 11" width="1195" src="https://user-images.githubusercontent.com/4256471/177011128-3da530d1-214c-4411-8676-59e87f34dfc7.png">

oh, so sorry didn't realize that.
I will fix it in an hour

**Comment by warren30815** [comment]
It works! Thank you very much
