### ISSUE TITLE
Change button titles

### ISSUE THREAD

**Issue by DominikGanic** [fatihsolhan/v-onboarding#38]
Hi, I really love this plugin. Could you please add props to change the buttons titles like "Next", "Previous" and "Finish"? :)
And maybe a slot to change the close icon?

That would save me the time to manually create a new popover template instead of using popper and the defaults which are pretty good and easy to re-design and customize.

I'd like to translate the buttons into german. I think this shouldn't be a big deal and can be very fast changed. Thanks! :D

**Comment by fatihsolhan** [comment]
Hi @DominikGanic thank you for your interest in `v-onboarding` ❤️ 

The purpose of customizable UI was to avoid custom props for each button. Have you checked our Custom UI example?
https://v-onboarding-docs.fatihsolhan.com/examples/custom-ui You can customize the steps as you wish easily.

If you want to use the default look but with customization, I would suggest grabbing the default step's HTML code [from here](https://github.com/fatihsolhan/v-onboarding/blob/main/src/components/VOnboardingStep.vue#L8) and editing it.

Please let me know if this helps

**Comment by fatihsolhan** [comment]
closing the issue. @DominikGanic, feel free to reopen if the provided solution didn't help

**Comment by fatihsolhan** [comment]
Hey, @DominikGanic just wanted to let you know that I just released the `2.1.0` update that allows you to change button titles.

https://github.com/fatihsolhan/v-onboarding/releases/tag/v2.1.0

**Comment by DominikGanic** [comment]
Hi @fatihsolhan, you‘re awesome. Thanks for this! Will immediately take note if this tomorrow at work. Thanks for your engagement and taking care of us. :)

**Comment by fatihsolhan** [comment]
> Hi @fatihsolhan, you‘re awesome. Thanks for this! Will immediately take note if this tomorrow at work. Thanks for your afford and taking care of us. :)

Thanks for the kind words :) Glad to help
