### ISSUE TITLE
Possible to style highlighted element?

### ISSUE THREAD

**Issue by jimmiejackson414** [fatihsolhan/v-onboarding#39]
**Is your feature request related to a problem? Please describe.**
I've been unable to figure out a way to style the highlighted element from either the docs or looking through the rendered DOM.

**Describe the solution you'd like**
The ability to style the highlighted element (I'm looking to add simple things such as padding and rounded corners).

**Describe alternatives you've considered**
I've looked through the docs as well as what is being rendered in the DOM.

**Additional context**
![Screen Shot 2022-07-15 at 3 21 39 PM](https://user-images.githubusercontent.com/93394140/179318839-08a03b3c-9ad6-4696-b468-a5d4c05614db.png)

**Comment by fatihsolhan** [comment]
Hi, @jimmiejackson414 thank you for your interest in `v-onboarding` ❤️

We have an `attachTo.classList` option in `steps`, you could add some classes to style highlighted element.
See: https://v-onboarding-docs.fatihsolhan.com/props/steps

Please let me know if it helps

**Comment by jimmiejackson414** [comment]
I'd noticed that and tried styling it with that route, but adding things like padding messed with the layout quite a bit. I think I was mostly unsure of whether it was creating a new DOM element over the top of the element itself, and whether I could style that new DOM element but it doesn't sound like that's the case. I'll give this another shot, thanks!

**Comment by fatihsolhan** [comment]
Hey @jimmiejackson414, you meant adding padding and border radius to the corners of the overlay element as in SS below?
If so, it is just an SVG actually. If you want, I could try to add options for rounding corners and adding padding etc
![image](https://user-images.githubusercontent.com/22654053/179421457-09107faa-bf59-4269-98d9-682df18c3e1b.png)

**Comment by jimmiejackson414** [comment]
@fatihsolhan yes that's correct, that would be incredible!

**Comment by fatihsolhan** [comment]
Hey @jimmiejackson414 

You can now add padding and border-radius to overlay element.
See `overlay` option: https://v-onboarding-docs.fatihsolhan.com/props/options

**Comment by jimmiejackson414** [comment]
Works beautifully, thanks a ton!
