### ISSUE TITLE
Missing "./src/types/StepEntity" export in "v-onboarding" package

### ISSUE THREAD

**Issue by jimmiejackson414** [fatihsolhan/v-onboarding#42]
**Describe the bug**
I'm receiving the error `Missing "./src/types/StepEntity" export in "v-onboarding" package` when starting local development server.

**To Reproduce**
1. Use latest v.2.0.0 version of this library
2. Add `import type { StepEntity } from 'v-onboarding/src/types/StepEntity'` to .ts file
3. Start local Vite dev server
4. Error appears during local startup

**Additional context**
I don't believe this error occurred with the previous version of this library, was the StepEntity type export changed?

**Comment by jimmiejackson414** [comment]
Dumb mistake on my part. I hadn't merged code from the branch containing the v2 upgrade into my current branch, which meant I was still on the previous version! Closing this issue.

**Comment by fatihsolhan** [comment]
Hey @jimmiejackson414, no worries :) I was looking into the issue. I'm glad you solved it 👍

**Comment by jimmiejackson414** [comment]
@fatihsolhan thanks for being so responsive, and for the killer library!
