### ISSUE TITLE
Allow to translate buttons text

### ISSUE THREAD

**Issue by jeremyVignelles** [fatihsolhan/v-onboarding#44]
**Is your feature request related to a problem? Please describe.**
I'm creating a website in french, so I need buttons in french

**Describe the solution you'd like**
Either translations should be embedded in the npm package, or there should be a way to pass the buttons labels in the options.

**Describe alternatives you've considered**
Overriding the template, which is a tedious task, just to change a button label.

**Comment by fatihsolhan** [comment]
Hey @jeremyVignelles 

I'll release an update for this at the weekend.
