### ISSUE TITLE
Close Button Event - OnClosed

### ISSUE THREAD

**Issue by DominikGanic** [fatihsolhan/v-onboarding#53]
Hi, I'm requesting here a simple integration to provide an event which fires once I click on the close button. It would be great if there would be a option to define a prompt to ask if the user really wants to close the guide instead of directly closing it.

I'd love to integrate this to set a cookie on his browser to hide the guide once he reloads / visits our page again. As well in the backend I will save it so it will never ever show again.

So if he closes the guide accidently, it can't be recovered as it's hidden from now. So it would be great to ask for his permission to really close it or to cancel the closing.

I hope you understood my request. Even though if the prompt is a big deal - no doubts - it would be good enough to have an event which fires once I click the close button - that's all I need.

Thanks again for your effort. Let's make this plugin more great as it already is! :)

**Comment by fatihsolhan** [comment]
Hi, @DominikGanic thanks a lot for your request and kind words.
That callback does make sense. There is already PR https://github.com/fatihsolhan/v-onboarding/pull/48 which adds the `exit` event.
I will review and merge it asap. Having a super busy week, that's why couldn't find time and merge that.

`v-onboarding` will only emit the `close/exit` event. I think letting the users implement their own prompt makes more sense because that looks out of the `v-onboarding`'s scope for me. I might be wrong, would love to hear your opinions as well.

**Comment by DominikGanic** [comment]
Thanks again for your answer and don't worry about me, just take your time and relax if you're really busy. :)

I think it would be nice if I could catch the close event and inject somehow into it. Like if the close event has been called, but I haven't injected any custom method like prompts / sweetalerts / whatever, it should directly close the boarding. Otherwise, if I've injected my custom prompt, there should be a provided argument function like Close() which I can call if the prompt has been accepted.

Something like this:

```
@close="BoardingClose"

const BoardingClose (CloseBoarding) => {
// ask for prompt here...
// if accepted: save as cookie that the boarding has been cancelled by the user
CloseBoarding();
};
```

**Comment by fatihsolhan** [comment]
I would suggest adding your own close listener to your custom UI button like this


```vue
<template>
<VOnboardingWrapper>
  <VOnboardingStep>
    // ...
    <button class="close" @click="onClickClose">X</button>
    // ...
  </VOnboardingStep>
</VOnboardingWrapper>

</template>
<script>
const { start, finish } = useVOnboarding()

const showPrompt = ref(false)

const onClickClose = () => {
    showPrompt.value = true

  // apply logic here
 
 // if decided to end onboarding:
 finish()

 // if decided to stay
 showPrompt.value = false
}
</script>
```
