### ISSUE TITLE
Exit emit doesnt working

### ISSUE THREAD

**Issue by denizzeybek** [fatihsolhan/v-onboarding#60]
I called exit emit like below.
  <VOnboardingWrapper ref="wrapper" :steps="steps" :options="options" @exit="onExit"/>

  const onExit = () => {
      console.log('onexit');
  };

But emit doesnt call onExit method.

**Comment by fatihsolhan** [comment]
Hi @denizzeybek thank you for catching this bug. It is fixed in the new release but please make sure you are using the lowercase `@exit` not the `@EXIT`.
