### ISSUE TITLE
exit / finish emits required

### ISSUE THREAD

**Issue by DominikGanic** [fatihsolhan/v-onboarding#66]
Hi, there is an emit for "exit". But why not for "finish"?

As example: When I click the "X" button on top right of my onboarding, it executes the @exit=".." emit. But when the last step has been reached, there is a "Finish" button which executes as well the @exit=".." emit. But it should emit a @finish=".." function.

The reason for this is, I'm trying to seperate a cancel / finish function to save the state in my database. Now I have to write a complex condition to check if it's finished or has been exited manually by user. :/

Thanks!

**Comment by fatihsolhan** [comment]
Hey @DominikGanic, you are right. I have some other bug fixes as well, I'll add this to my list. They should be released this weekend

**Comment by DominikGanic** [comment]
I've added a comment at this commit:
https://github.com/fatihsolhan/v-onboarding/commit/ecb32258a5b826a66ceb6006438be9cbe1f2c12e

Looks like the following line there causes problems, since I've updated the package today.

`index.2a3644af.js:1 DOMException: Failed to execute 'setAttribute' on 'Element': 'finish,' is not a valid attribute name.`

![image](https://user-images.githubusercontent.com/13388387/220643758-62870d50-92d1-49b0-bafb-b62a9bf07525.png)

**Comment by DominikGanic** [comment]
Thanks mate! Happens to the best ;)!
