### ISSUE TITLE
Clicking 'X' is emitting, but not closing.

### ISSUE THREAD

**Issue by shealavington** [fatihsolhan/v-onboarding#72]
Upon clicking X on the popover, the tool does not close as expected.
Pressing 'Finish' at the end works just fine.

I would expect clicking 'X' to close the onboard.

![image](https://github.com/fatihsolhan/v-onboarding/assets/16869302/8a182e82-e637-4a2c-ac34-2b2504bb5172)

Versions:
Vue: 3
Oboarding: v2.4.0

**Comment by shealavington** [comment]
Debatable if this is a bug actually... Personally, that's expected behaviour but I've found I can fix it by calling the finish from the exit emit... So, it's really up to others on what is expected functionality.

```vue
<script setup>
import { ref, onMounted } from 'vue'

import { VOnboardingWrapper, useVOnboarding } from 'v-onboarding'
import 'v-onboarding/dist/style.css'

const wrapper = ref(null)
const onboarding = useVOnboarding(wrapper)
const onboardingSteps = [ ... myStepsHere ]

onMounted((): void => onboarding.start())
</script>
<template>
<VOnboardingWrapper 
    ref="wrapper" 
    @exit="onboarding.finish()"
    :steps="onboardingSteps" 
  />
</template>
```

**Comment by fatihsolhan** [comment]
@shealavington that part is kinda not clear to me as well 😄 

I did it that way because people wanted to listen the exit event and maybe prevent exiting or finish some async task before finishing the onboarding. But now it doesnt exit by default when you click on X

Not sure if I have to do something about it or just leave it as is..

**Comment by rozsazoltan** [comment]
## New idea in response to the problem

In my opinion, it's a good idea to listen to the event by default, but in the end, regardless of what I set for the emit, the tutorial should be completed.

In addition, two new settings should be created:

1. `options.hideButtons.close` (Boolean, default: false): would allow for hiding the X without having to create a custom template
2. `options.autoFinishByClose` (Boolean, default: true): by default, the finish() function runs when the Close button is clicked, but we should provide an option to enable/disable its execution.

[options](https://v-onboarding-docs.fatihsolhan.com/props/options)

## Implementation
### By Default

The X appears and clicking on it makes the event listenable, but after this, the finish() function would be executed.

```js
const options = {
    hideButtons: {
        close: false // default value
    },
    autoFinishByClose: true // default value
}
```
```html
<VOnboardingWrapper 
    ref="wrapper"
    :options="options" <!-- not required by default using -->
    :steps="onboardingSteps" 
 />
 ```
 
 ### If I don't need automatic finish()
 
 ```js
const options = {
    autoFinishByClose: false // here
}
```
```html
<VOnboardingWrapper 
    ref="wrapper"
    :options="options" <!-- required -->
    :steps="onboardingSteps" 
 />
  ```
  
  ### If I don't need to display the Close (X) button
 
 ```js
const options = {
    hideButtons: {
        close: true // here
    },
}
```
```html
<VOnboardingWrapper 
    ref="wrapper"
    :options="options" <!-- required -->
    :steps="onboardingSteps" 
 />
  ```

### Also, our @exit emit remains...

...with which we can execute anything upon detecting an exit. **However, by default, we don't need to manually implement the execution of the finish() function.**

```html
<VOnboardingWrapper 
    ref="wrapper"
    @exit="detectExitFromTutorial(...)"
    :steps="onboardingSteps"
/>
  ```

**Comment by shealavington** [comment]
Haha no problem, personally, I think that even on clicking X (exit) it should always close the overlay. 
Though, I can understand people wanting the `@exit` and `@finished` emits being emitted as two events rather than one.

**For example:**
I have 10 steps 
A user reached step 5 and exits early (presses 'X'), 
I listen for `@ exit` and store their last index, 
When user next reloads, I reopen from step 5 
I listen for `@ finish` then mark a local storage option to never re-open for the user again.

**Comment by fatihsolhan** [comment]
Hey @shealavington and @rozsazoltan,

Thanks @shealavington for flagging the issue, really appreciate it.

And @rozsazoltan, good work on finding a solution and for the PR. It's been merged successfully today.

All sorted now, so I'm closing this issue. Thanks again to both of you for your help!
