### ISSUE TITLE
Add delay and hide / autoHide

### ISSUE THREAD

**Issue by Farnsi** [fatihsolhan/v-onboarding#76]
on.beforeStep should be executed normally, the step should only be displayed after the delay.

example
```js
const steps = [
  {
    attachTo: { element: '#id1' },
    content: { title: 'Title 1'  },
    hide: true // defaults to true, hides the step when the next step has a delay
  },
  {
    delay: 2000,
    attachTo: { element: '#id2' },
    content: { title: 'Title 2'  },
  }
```

On start it shows step 1, click `next`, it hides the current step 1, cause step 2 has a delay.
Step 2 on.beforeStep is executed (e.g. do things like open a navigation with animation).
After 2000 miliseconds step 2 appears.

**Comment by rozsazoltan** [comment]
I don't know where this would be useful...

**Comment by rozsazoltan** [comment]
Yes, it would be useful to wait for the end of scrolling when creating an SVG in the case of "smooth" scrolling, but the mentioned animation is also a good example.

**Comment by fatihsolhan** [comment]
I suggest you to use `onBeforeStep` for adding delay before the step
```js
on: {
  async beforeStep() {
    await new Promise(resolve => setTimeout(resolve, 1000))
  }
}
```

I'll add an option to hide the step until on.beforeStep is executed
