### ISSUE TITLE
toRefs expects a reactive object but received a plain one

### ISSUE THREAD

**Issue by FabianWassermann** [fatihsolhan/v-onboarding#84]
**Describe the bug**
The onboarding tour is not starting because of this warning: "toRefs() expects a reactive object but received a plain one."

**To Reproduce**
1. Vue Version 3.3.0
2. install and setup like in documentation
4. See warning

**Expected behavior**
The tour should start.

**Screenshots**
![image](https://github.com/fatihsolhan/v-onboarding/assets/53076710/038583ed-9781-48d4-9472-d902f19deb6d)
![image](https://github.com/fatihsolhan/v-onboarding/assets/53076710/728070c3-c3bd-4616-b9ab-acce7c4d8a4d)
![image](https://github.com/fatihsolhan/v-onboarding/assets/53076710/1c02ed1e-fc31-46a8-84ff-3bd5ae30bf31)

**Desktop (please complete the following information):**
 - OS: [e.g. Win10]
 - Browser [e.g. chrome, brave]

**Comment by fatihsolhan** [comment]
Thank you @FabianWassermann, this is fixed with #80
