### ISSUE TITLE
A11y issue - focus should move to the onboarding card when start() is called

### ISSUE THREAD

**Issue by chriskulwik** [fatihsolhan/v-onboarding#88]
**Describe the bug**
This is an accessibility issue. 

issue 1: 
For a user who is not able to use a mouse, they navigate around the page using the tab key to focus on different elements. This doesn't work well.  This also happens when clicking next or back.

issue 2: 
Another note, focus should be trapped within the onboarding item once focus is established in there. 

**To Reproduce**
issue 1:
Once start() is called, focus should be moved to inside the onboarding item, this is not the case. Currently, start() is called, but the focus is not moved, making it so this user has to hit tab many times, first focusing on every element on the page before focus is transferred to the onboarding item.

issue 2:
Say for example, if I have a close button, back button, and a next button: 
- say we have focus on close 
- hit tab 
- now focus is on back
- hit tab
- now focus is on next, 
- hit tab
- focus goes to the rest of the web page

**Expected behavior**

issue 1:
Focus should be transferred to the onboarding item when next, back, or start() is called.

issue 2:
Focus should be trapped in the onboarding item
- say we have focus on close 
- hit tab 
- now focus is on back
- hit tab
- now focus is on next, 
- hit tab
- focus should go back to close

**Screenshots**

**Desktop (please complete the following information):**
 - OS: mac
 - Browser: chrome
 - Version: package version 2.6.0

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rozsazoltan** [comment]
Wow, that's a completely valid observation! A real issue that needs to be addressed.

**Comment by fatihsolhan** [comment]
Hi all! Thank you for you interest and potential suggestions for this issue, I appreciate it. I've implemented a focus-trap feature and it should be live soon
