### ISSUE TITLE
vue__WEBPACK_IMPORTED_MODULE_1__.createElementVNode) is not a function

### ISSUE THREAD

**Issue by DatenManu** [fatihsolhan/v-onboarding#96]
**Describe the bug**
Followed instruction from basic example, started app, crashed

**Expected behavior**
not to crash

**Screenshots**
![image](https://github.com/fatihsolhan/v-onboarding/assets/159016268/44b4fb7b-e688-4d29-8ad8-2d40dbba5f5d)
![image](https://github.com/fatihsolhan/v-onboarding/assets/159016268/38a0c0a9-8770-4117-a065-0a4bb27a6ddc)
![image](https://github.com/fatihsolhan/v-onboarding/assets/159016268/546e2676-7602-48f1-93e2-0145e034b609)
![image](https://github.com/fatihsolhan/v-onboarding/assets/159016268/d93bbc87-79f0-4770-88da-4873e250aac1)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome 
 - Version: 122.0.6261.96

**Comment by fatihsolhan** [comment]
Hi, are you using vue2? This package is only compatible with vue3
