### ISSUE TITLE
Cannot focus to the attached element input after version 2.7.0

### ISSUE THREAD

**Issue by ian-ng** [fatihsolhan/v-onboarding#99]
#88 caused this bug.

After version 2.7.0, the input elements cannot be focused, probably the useFocusTrap force to focus on the step only. 
It should be allowed to focus on the attached element also.
Even applied the `overlay.preventOverlayInteraction = false`, still cannot focus to the attached element.

**Comment by ian-ng** [comment]
In addition, when focusing on the input in the bottom area input using a mobile device, the keyboard overlays on the input area.

**Comment by fatihsolhan** [comment]
Hi @ian-ng! 👋

This issue has been resolved and included in v2.9.0.

Feel free to reopen if you encounter any issues. Thanks for your patience! 🙌
